object DependenciesVersions {
    const val ACCOMPANIST = "0.30.1"
    const val ACT_COMPOSE = "1.7.2"
    const val ANNOTATION = "1.6.0"
    const val COMPOSE_BOM = "2023.05.01"
    const val CONSTRAINT_LAYOUT = "1.0.1"
    const val CORE = "1.10.1"
    const val HILT = "2.44"
    const val HILT_NAVIGATION = "1.0.0"
    const val KOTLIN_BOM = "1.8.10"
    const val LIFECYCLE = "2.6.1"
    const val MOSHI = "1.14.0"
    const val RETROFIT = "2.9.0"
    const val STETHO = "1.6.0"
}